### ISSUE TITLE
Using d-pad as steering and not Steering Axis

### ISSUE THREAD

**Issue by w1lla** [resir014/TMViz#31]
Hi,

When using d-pad to steer left/right i still can see the Steering Axis even though i did not set them.

D-pad input goes up down, left right when using Steering Axis.

Controller: NACON Revolution Unlimited Pro.

When i use the Steering Axis just as a test it shows up, even if its not being binded on the webpage.

Source:
https://tmviz.vercel.app/overlay?accelerateButton=0&accelerateColor=%231fc791&brakeButton=2&brakeColor=%23ee0000&controllerIndex=0&steeringColor=%23cb891d&steeringDeadzone=0.01&steeringLeftButton=14&steeringRightButton=15&version=1

on gamepadtester.com:

AXIS 9
3.28571 no usage:

press d-pad left:
AXIS 9
0.71429

press d-pad right:
AXIS 9
3.28571

For Steering Axis my controller uses:

Axis 0.

**Comment by resir014** [comment]
@w1lla When steering axis is not set, it falls back to Axis 0 at the moment. Removing the fallback should be easy enough.
